#!/usr/local/bin/python3

# POC implementation that focuses only on the network login without taking any parameters and
# outputting only to stdout and stderr.
# ✓ Test DNS name lookup to 'accezz.io'
# ✓ Test DNS name lookup to 'yahoo.com'
# - Measure HTTP bandwidth to <file-URL>
# - Measure HTTPS bandwidth to <file-URL>

import socket

def dns_lookup(url_str):
    print('DNS LOOKUP %s: ' % url_str, end='')
    print(socket.gethostbyname(url_str))
    
dns_lookup('accezz.io')
dns_lookup('yahoo.com')
