#!/usr/local/bin/python3

# POC implementation that focuses only on the network login without taking any parameters and
# outputting only to stdout and stderr.
# - Test DNS name lookup to 'accezz.io'
# - Test DNS name lookup to 'yahoo.com'
# - Measure HTTP bandwidth to <file-URL>
# - Measure HTTPS bandwidth to <file-URL>
